Use PlaceOrder instead of CreateObject for virtual guests with custom…
softlayer/terraform-provider-softlayer pull request #53
Opened 2016-11-25 10:18 UTC by matevzmihalic

… image and multiple disks. Fixes #50

2016-11-25 22:46 UTC, renier commented
@matevzmihalic Are you not able to generate the order template without an os reference code but with the image id instead (or with the image global identifier)?

2016-11-28 09:09 UTC, matevzmihalic commented
If I use image id and multiple disks to generate the order template I get the same error as before (`Invalid value provided for 'blockDevices'. Block devices may not be provided when using an image template`).

2016-11-29 00:16 UTC, renier requested changes

2016-11-29 00:16 UTC, renier commented on softlayer/resource_softlayer_virtual_guest.go
> +		// Find a temporary OS reference code that will be used to generate a template
You can use something like "UBUNTU_LATEST" which is a code that won't be going away any time soon.

2016-11-29 08:16 UTC, matevzmihalic commented on softlayer/resource_softlayer_virtual_guest.go
> +		// Find a temporary OS reference code that will be used to generate a template
Done.

2016-11-30 15:27 UTC, renier requested changes

2016-11-30 15:27 UTC, renier commented on softlayer/resource_softlayer_virtual_guest.go
> +				template.Prices = append(template.Prices[:i], template.Prices[i+1:]...)
this continual stitching of the array may result in a high-ish number of memory allocations.

what if you create a separate price array separately that has all the prices whose item description do not contain the world ubuntu. then you set it `template.Prices = ubuntuLessPricess`

2016-12-05 12:52 UTC, matevzmihalic commented on softlayer/resource_softlayer_virtual_guest.go
> +				template.Prices = append(template.Prices[:i], template.Prices[i+1:]...)
Done.

2016-12-06 08:02 UTC, merged